
version: '3.8'

services:
  clustering-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CLUSTERING_TOKEN=secure-token-123
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
